Correct example in documentation of S3 parameters (#275)
When using the key "Cache-Control" in AWS_S3_OBJECT_PARAMETERS, I got this error:

> ValueError: Invalid extra_args key 'Cache-Control', must be one of: ACL, CacheControl, ContentDisposition, ContentEncoding, ContentLanguage, ContentType, Expires, GrantFullControl, GrantRead, GrantReadACP, GrantWriteACP, Metadata, RequestPayer, ServerSideEncryption, StorageClass, SSECustomerAlgorithm, SSECustomerKey, SSECustomerKeyMD5, SSEKMSKeyId, WebsiteRedirectLocation

I fixed it by replacing "Cache-Control" with "CacheControl".

I fixed the documentation to use the correct key, and to remove the word arbitrary, since it doesn't seem arbitrary to me.